<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::table('users', function(Blueprint $t){$t->string('username')->nullable()->unique()->after('name');$t->string('mobile',15)->nullable()->unique()->after('username');$t->boolean('active')->default(true);});
 Schema::create('customers',function(Blueprint $t){$t->id();$t->string('customer_code')->unique();$t->string('name');$t->string('company_name')->nullable();$t->string('mobile',15)->index();$t->string('phone',20)->nullable();$t->text('address');$t->string('province')->nullable();$t->string('city')->nullable();$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->text('description')->nullable();$t->timestamps();});
 Schema::create('products',function(Blueprint $t){$t->id();$t->string('name');$t->string('code')->unique();$t->string('unit')->default('kg');$t->unsignedBigInteger('price');$t->boolean('active')->default(true);$t->timestamps();});
 Schema::create('orders',function(Blueprint $t){$t->id();$t->string('order_number')->unique()->index();$t->foreignId('customer_id')->constrained()->restrictOnDelete()->index();$t->foreignId('visitor_id')->nullable()->constrained('users')->nullOnDelete()->index();$t->date('order_date');$t->date('delivery_date')->nullable()->index();$t->decimal('total_weight',10,3)->default(0);$t->unsignedBigInteger('total_amount')->default(0);$t->string('status')->default('pending')->index();$t->string('delivery_code_hash')->nullable();$t->timestamp('delivery_code_created_at')->nullable();$t->timestamp('delivery_code_expires_at')->nullable();$t->unsignedTinyInteger('delivery_code_attempts')->default(0);$t->timestamp('delivery_code_locked_at')->nullable();$t->timestamp('delivery_code_verified_at')->nullable();$t->timestamp('delivery_started_at')->nullable();$t->timestamp('delivered_at')->nullable();$t->foreignId('delivered_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('delivery_failed_at')->nullable();$t->string('failure_reason')->nullable();$t->text('notes')->nullable();$t->timestamps();});
 Schema::create('order_items',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->decimal('quantity',10,3);$t->decimal('weight',10,3)->default(0);$t->unsignedBigInteger('unit_price');$t->unsignedBigInteger('total_price');$t->timestamps();});
 Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('visitor_id')->constrained('users')->restrictOnDelete();$t->string('method');$t->unsignedBigInteger('amount');$t->string('reference_number')->nullable()->index();$t->string('card_last_four',4)->nullable();$t->string('bank_name')->nullable();$t->string('cheque_number')->nullable();$t->date('cheque_due_date')->nullable();$t->string('issuer_name')->nullable();$t->string('cheque_image_path')->nullable();$t->date('promise_date')->nullable();$t->text('description')->nullable();$t->timestamps();});
 Schema::create('delivery_logs',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('visitor_id')->nullable()->constrained('users')->nullOnDelete();$t->string('action');$t->text('description')->nullable();$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->text('device_info')->nullable();$t->string('ip_address',45)->nullable();$t->timestamp('created_at')->useCurrent();});
 Schema::create('delivery_code_attempts',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('visitor_id')->constrained('users')->restrictOnDelete();$t->boolean('success');$t->string('ip_address',45)->nullable();$t->text('device_info')->nullable();$t->timestamp('created_at')->useCurrent();});
 Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action');$t->string('subject_type')->nullable();$t->unsignedBigInteger('subject_id')->nullable();$t->json('metadata')->nullable();$t->string('ip_address',45)->nullable();$t->text('device_info')->nullable();$t->timestamp('created_at')->useCurrent();});
 Schema::create('settings',function(Blueprint $t){$t->id();$t->string('key')->unique();$t->text('value')->nullable();$t->timestamps();});
 } public function down():void {Schema::dropIfExists('settings');Schema::dropIfExists('audit_logs');Schema::dropIfExists('delivery_code_attempts');Schema::dropIfExists('delivery_logs');Schema::dropIfExists('payments');Schema::dropIfExists('order_items');Schema::dropIfExists('orders');Schema::dropIfExists('products');Schema::dropIfExists('customers');Schema::table('users',fn(Blueprint $t)=>$t->dropColumn(['username','mobile','active']));} };
