<?php
namespace App\Http\Controllers\Api;
use App\Enums\OrderStatus;use App\Models\{AuditLog,Order,Payment};use App\Services\DeliveryService;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class OrderController extends ApiController {public function __construct(private DeliveryService $delivery){}
 public function index(Request $r){$q=Order::with('customer')->where('visitor_id',$r->user()->id)->orderBy('delivery_date');if($r->filled('date'))$q->whereDate('delivery_date',$r->date);return $this->ok($q->paginate(20),'سفارش‌ها دریافت شد.');}
 public function show(Request $r,Order $order){$this->authorize('view',$order);$order->load('customer','items.product','payments');$this->audit($r,'view_order',$order);return $this->ok($order,'جزئیات سفارش دریافت شد.');}
 public function start(Request $r,Order $order){$this->delivery->ensureDeliverable($order,$r);if(!in_array($order->status,[OrderStatus::Assigned,OrderStatus::Pending]))return $this->fail('شروع تحویل در وضعیت فعلی ممکن نیست.',[],409);$order->update(['status'=>OrderStatus::OutForDelivery,'delivery_started_at'=>now()]);$this->delivery->log($order,$r->user()->id,'start_delivery');return $this->ok($order->fresh(),'تحویل آغاز شد.');}
 public function verify(Request $r,Order $order){$r->validate(['code'=>'required|digits:6']);$result=$this->delivery->verify($order,$r);return $result['verified']?$this->ok($result,'کد تحویل تأیید شد.'):$this->fail('کد تحویل صحیح نیست.',['remaining_attempts'=>$result['remaining']],422);}
 public function payment(Request $r,Order $order){$this->delivery->ensureDeliverable($order,$r);abort_unless($order->status===OrderStatus::CodeVerified,422,'ابتدا کد تحویل را تأیید کنید.');$d=$r->validate(['method'=>'required|in:card,cash,cheque,credit,bank_transfer,prepaid','amount'=>'required|integer|min:0','reference_number'=>'nullable|string|max:100','card_last_four'=>'nullable|digits:4','bank_name'=>'nullable|string|max:100','cheque_number'=>'nullable|string|max:100','cheque_due_date'=>'nullable|date','issuer_name'=>'nullable|string|max:150','promise_date'=>'nullable|date','description'=>'nullable|string|max:2000']);$payment=Payment::updateOrCreate(['order_id'=>$order->id],$d+['visitor_id'=>$r->user()->id]);$this->delivery->log($order,$r->user()->id,'payment_registered');return $this->ok($payment,'روش تسویه ثبت شد.',201);}
 public function complete(Request $r,Order $order){$this->delivery->ensureDeliverable($order,$r);$r->validate(['idempotency_key'=>'required|string|max:128']);return DB::transaction(function()use($order,$r){$order->refresh();abort_if($order->status===OrderStatus::Delivered,409,'این سفارش قبلاً تحویل شده است.');abort_unless($order->status===OrderStatus::CodeVerified&&$order->payments()->exists(),422,'کد یا روش تسویه ثبت نشده است.');$tracking='DLV-'.now()->format('Y').'-'.str_pad((string)$order->id,6,'0',STR_PAD_LEFT);$order->update(['status'=>OrderStatus::Delivered,'delivered_at'=>now(),'delivered_by'=>$r->user()->id,'notes'=>trim(($order->notes??'')."\nTracking: $tracking")]);$this->delivery->log($order,$r->user()->id,'delivery_completed',$tracking);$this->audit($r,'delivery_completed',$order);return $this->ok(['tracking_number'=>$tracking,'order'=>$order->fresh()],'تحویل با موفقیت ثبت شد.');});}
 public function failed(Request $r,Order $order){$this->delivery->ensureDeliverable($order,$r);$d=$r->validate(['reason'=>'required|in:customer_absent,rejected,amount_issue,quality_issue,wrong_address,no_response,rescheduled,other','description'=>'required_if:reason,other|nullable|string|max:2000']);$order->update(['status'=>OrderStatus::DeliveryFailed,'delivery_failed_at'=>now(),'failure_reason'=>$d['reason']]);$this->delivery->log($order,$r->user()->id,'delivery_failed',$d['description']??$d['reason']);return $this->ok($order->fresh(),'عدم تحویل ثبت شد.');}
 private function audit(Request $r,string $action,Order $o):void{AuditLog::create(['user_id'=>$r->user()->id,'action'=>$action,'subject_type'=>Order::class,'subject_id'=>$o->id,'ip_address'=>$r->ip(),'device_info'=>$r->attributes->get('device_info'),'created_at'=>now()]);}}
